/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as MainIndexImport } from './routes/_main/index'
import { Route as MainTvShowsImport } from './routes/_main/tvShows'
import { Route as MainMoviesImport } from './routes/_main/movies'

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const MainTvShowsRoute = MainTvShowsImport.update({
  id: '/tvShows',
  path: '/tvShows',
  getParentRoute: () => MainRoute,
} as any)

const MainMoviesRoute = MainMoviesImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => MainRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_main/movies': {
      id: '/_main/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MainMoviesImport
      parentRoute: typeof MainImport
    }
    '/_main/tvShows': {
      id: '/_main/tvShows'
      path: '/tvShows'
      fullPath: '/tvShows'
      preLoaderRoute: typeof MainTvShowsImport
      parentRoute: typeof MainImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
  }
}

// Create and export the route tree

interface MainRouteChildren {
  MainMoviesRoute: typeof MainMoviesRoute
  MainTvShowsRoute: typeof MainTvShowsRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainMoviesRoute: MainMoviesRoute,
  MainTvShowsRoute: MainTvShowsRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof MainRouteWithChildren
  '/movies': typeof MainMoviesRoute
  '/tvShows': typeof MainTvShowsRoute
  '/': typeof MainIndexRoute
}

export interface FileRoutesByTo {
  '/movies': typeof MainMoviesRoute
  '/tvShows': typeof MainTvShowsRoute
  '/': typeof MainIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_main': typeof MainRouteWithChildren
  '/_main/movies': typeof MainMoviesRoute
  '/_main/tvShows': typeof MainTvShowsRoute
  '/_main/': typeof MainIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/movies' | '/tvShows' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/movies' | '/tvShows' | '/'
  id: '__root__' | '/_main' | '/_main/movies' | '/_main/tvShows' | '/_main/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_main"
      ]
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/movies",
        "/_main/tvShows",
        "/_main/"
      ]
    },
    "/_main/movies": {
      "filePath": "_main/movies.tsx",
      "parent": "/_main"
    },
    "/_main/tvShows": {
      "filePath": "_main/tvShows.tsx",
      "parent": "/_main"
    },
    "/_main/": {
      "filePath": "_main/index.tsx",
      "parent": "/_main"
    }
  }
}
ROUTE_MANIFEST_END */
