/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TvShowsImport } from './routes/tvShows'
import { Route as MoviesImport } from './routes/movies'
import { Route as IndexImport } from './routes/index'
import { Route as WatchIdImport } from './routes/watch/$id'
import { Route as DetailTypeIdImport } from './routes/detail/$type/$id'

// Create/Update Routes

const TvShowsRoute = TvShowsImport.update({
  id: '/tvShows',
  path: '/tvShows',
  getParentRoute: () => rootRoute,
} as any)

const MoviesRoute = MoviesImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WatchIdRoute = WatchIdImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRoute,
} as any)

const DetailTypeIdRoute = DetailTypeIdImport.update({
  id: '/detail/$type/$id',
  path: '/detail/$type/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesImport
      parentRoute: typeof rootRoute
    }
    '/tvShows': {
      id: '/tvShows'
      path: '/tvShows'
      fullPath: '/tvShows'
      preLoaderRoute: typeof TvShowsImport
      parentRoute: typeof rootRoute
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdImport
      parentRoute: typeof rootRoute
    }
    '/detail/$type/$id': {
      id: '/detail/$type/$id'
      path: '/detail/$type/$id'
      fullPath: '/detail/$type/$id'
      preLoaderRoute: typeof DetailTypeIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movies': typeof MoviesRoute
  '/tvShows': typeof TvShowsRoute
  '/watch/$id': typeof WatchIdRoute
  '/detail/$type/$id': typeof DetailTypeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movies': typeof MoviesRoute
  '/tvShows': typeof TvShowsRoute
  '/watch/$id': typeof WatchIdRoute
  '/detail/$type/$id': typeof DetailTypeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/movies': typeof MoviesRoute
  '/tvShows': typeof TvShowsRoute
  '/watch/$id': typeof WatchIdRoute
  '/detail/$type/$id': typeof DetailTypeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/movies' | '/tvShows' | '/watch/$id' | '/detail/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movies' | '/tvShows' | '/watch/$id' | '/detail/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/movies'
    | '/tvShows'
    | '/watch/$id'
    | '/detail/$type/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoviesRoute: typeof MoviesRoute
  TvShowsRoute: typeof TvShowsRoute
  WatchIdRoute: typeof WatchIdRoute
  DetailTypeIdRoute: typeof DetailTypeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoviesRoute: MoviesRoute,
  TvShowsRoute: TvShowsRoute,
  WatchIdRoute: WatchIdRoute,
  DetailTypeIdRoute: DetailTypeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/movies",
        "/tvShows",
        "/watch/$id",
        "/detail/$type/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/movies": {
      "filePath": "movies.tsx"
    },
    "/tvShows": {
      "filePath": "tvShows.tsx"
    },
    "/watch/$id": {
      "filePath": "watch/$id.tsx"
    },
    "/detail/$type/$id": {
      "filePath": "detail/$type/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
